# DOCKER COMPOSE FOR DATEKEEPER
# Deploys datekeeper-backend and postgresql:14
# Make sure to remove port mappings from services in prod mode
version: "3.9"

services:
  db:
    container_name: datekeeper-postgres
    hostname: dk-postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=<PASSWORD HERE>
      - POSTGRES_USER=<USERNAME HERE>
      - POSTGRES_DB=<DB NAME HERE>
    volumes:
      - datekeeper-db:/var/lib/postgresql/data
    networks:
      default:
    expose:
      - 5432

  app:
    container_name: datekeeper-backend
    hostname: dk-backend
    image: datekeeper-backend:latest
    environment:
      - POSTGRES_PASSWORD=<PASSWORD HERE>
      - POSTGRES_USER=<USERNAME HERE>
      - POSTGRES_DB=<DB NAME HERE>
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      default:

  frontend:
    container_name: datekeeper-frontend
    image: datekeeper-frontend:latest
    expose:
      - 80
    ports:
      - 80:80
    networks:
      default:

volumes:
  datekeeper-db:

networks:
  # use this for prod
  #  default:
  #    external: true
  #    name: int-docker-net
  # route to localhost for testing locally
  default:
    driver: bridge
