# DOCKER COMPOSE FOR DATEKEEPER
# Deploys datekeeber-backend and postgresql:14
version: "3.9"

services:
  db:
    container_name: datekeeper-postgres
    hostname: dk-postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=aaa
      - POSTGRES_USER=aaa
      - POSTGRES_DB=proj
    volumes:
      - datekeeper-db:/var/lib/postgresql/data
    networks:
      default:
      #int-net:
    expose:
      - 5432

  app:
    container_name: datekeeper-backend
    hostname: dk-backend
    image: datekeeper-backend:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
     # int-net:
      default:

  frondent:
    container_name: datekeeper-frontend
    image: datekeeper-frontend:latest
    expose:
      - 80
    ports:
      - 80:80
    networks:
      default:
     # int-net:

volumes:
  datekeeper-db:

networks:
  #  default:
  #    external: true
  #    name: int-docker-net
  int-net:
  # route to localhost
  default:
    driver: bridge
